# Site Info
title: JINiOS
# tagline: 'Í≥µÎ∂ÄÍ∏∞Î°ù'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl: ""
url: https://jinios.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: JINiOS
  description: <strong>JIN+iOS</strong> <br> ‚ú®ü¶Ñ explore iOS & Swift üí´
  gravatar: # md5 hash of your email address
  contact:
    github: https://github.com/jinios
    # facebook:
    email: mailto:mayihelpu27@gmail.com
# Navigation (2nd level links supported)
nav:
  Categories:
    - '/blog/categories'
    #- { Categories: '/blog/categories' }
    - { TIL: '/blog/categories/#TIL' }
    - { Swift: '/blog/categories/#Swift' }
    - { JAVA: '/blog/categories/#JAVA' }
    - { Codesquad: '/blog/categories/#Codesquad' }
    - { Study: '/blog/categories/#Study' }
    - { Story: '/blog/categories/#Story' }
    - { Tags: '/blog/tags/' }
  # About me:
  #   - '/about/'
  Github Project:
    - 'https://github.com/jinios'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'Mijin' # leave blank if you don't want disqus
